spring:
  application:
    name: drug-service
  config:
    import:
    - optional:configserver:http://${CONFIG_URL:localhost}:8888
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
      
      